spring.application.name=h2databasedemo
# H2 DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console enable
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console